# Generated by Django 3.2.6 on 2022-05-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('adress', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('one', 'GRID'), ('two', 'PV'), ('three', 'HYBRID')], max_length=20)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
