# Generated by Django 3.2.6 on 2022-05-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='type',
            field=models.CharField(choices=[('GRID', 'GRID'), ('PV', 'PV'), ('HYBRID', 'HYBRID')], max_length=20),
        ),
    ]
