# Generated by Django 3.2.6 on 2022-05-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_plant_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeviceName', models.CharField(max_length=20)),
                ('voltage_V', models.FloatField()),
                ('Amperage_AMP', models.FloatField()),
                ('temperature_C', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slaveid', models.CharField(max_length=20)),
                ('modelname', models.CharField(max_length=20)),
                ('Alias', models.CharField(max_length=20)),
                ('Group', models.CharField(max_length=20)),
            ],
        ),
    ]
