# Generated by Django 3.2.6 on 2022-05-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_device_gateway'),
    ]

    operations = [
        migrations.CreateModel(
            name='new_Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeviceName', models.CharField(max_length=20)),
                ('slavename', models.CharField(max_length=20)),
                ('adress', models.CharField(max_length=20)),
                ('baud_rate', models.FloatField()),
                ('connection_type', models.CharField(choices=[('Rs485', 'Rs485'), ('lora', 'lora'), ('Other', 'Other')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='new_Gateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gatewayname', models.CharField(max_length=20)),
                ('slavename', models.CharField(max_length=20)),
                ('list_devices', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='new_Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('adress', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('ONGRID', 'ONGRID'), ('PV', 'PV'), ('HYBRID', 'HYBRID')], max_length=20)),
                ('location', models.CharField(max_length=50)),
                ('list_gateway', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('etude', 'Etude'), ('online', 'Online'), ('Other', 'Other')], max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='Gateway',
        ),
        migrations.DeleteModel(
            name='Plant',
        ),
    ]
