# Generated by Django 3.2.6 on 2022-05-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20220510_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_device',
            name='baud_rate',
            field=models.CharField(max_length=20),
        ),
    ]
