# Generated by Django 3.2.6 on 2022-05-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20220524_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monophase_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Voltage', models.FloatField()),
                ('Current', models.FloatField()),
                ('Active_Power', models.FloatField()),
                ('Apparent_Power', models.FloatField()),
                ('FP', models.FloatField()),
                ('frenquency', models.FloatField()),
            ],
        ),
    ]
