# Generated by Django 3.2.6 on 2022-05-26 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_monophase_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Monophase_test',
            new_name='test',
        ),
    ]
